{"name": "test_c006_03_error_message", "status": "passed", "steps": [{"name": "Logged_in user details, error message validation", "status": "passed", "start": 1631722850995, "stop": 1631722850995}], "start": 1631722850995, "stop": 1631722850995, "uuid": "fab66b17-f786-421e-a15e-1cf735b1171d", "historyId": "6cfb34e02079b5125765fc545d14b154", "testCaseId": "8ade8225be069c88657230f063a6331d", "fullName": "testcases.test_c006_current_logged_in_user_401#test_c006_03_error_message", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_c006_current_logged_in_user_401"}, {"name": "host", "value": "QupsAnik"}, {"name": "thread", "value": "13468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_c006_current_logged_in_user_401"}]}