{"name": "test_c004_03_error_message", "status": "passed", "steps": [{"name": "Signup unsuccessful, error message validation", "status": "passed", "start": 1631722850964, "stop": 1631722850964}], "start": 1631722850964, "stop": 1631722850964, "uuid": "c6190af6-39b9-47b9-969f-ef79aefc1796", "historyId": "3ea4268c25bafbaa22d10188981607d3", "testCaseId": "fd0ec5164fe26d94e6139dd0c1b1bdb8", "fullName": "testcases.test_c004_signin_400#test_c004_03_error_message", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_c004_signin_400"}, {"name": "host", "value": "QupsAnik"}, {"name": "thread", "value": "13468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_c004_signin_400"}]}