{"name": "test_c002_03_error_message", "status": "passed", "steps": [{"name": "Signup unsuccessful, error message validation", "status": "passed", "start": 1631722850948, "stop": 1631722850948}], "start": 1631722850948, "stop": 1631722850948, "uuid": "ce6d0341-56fe-4f3a-b8a7-5808fc4fad88", "historyId": "1f40305c7c9282f4030fe28dd196c1bf", "testCaseId": "02ca7cf529a6558dd1d0c7ab10572292", "fullName": "testcases.test_c002_signup_400#test_c002_03_error_message", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_c002_signup_400"}, {"name": "host", "value": "QupsAnik"}, {"name": "thread", "value": "13468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_c002_signup_400"}]}