{"name": "test_c004_04_error_field", "status": "passed", "steps": [{"name": "Signup unsuccessful, error field validation", "status": "passed", "start": 1631722808974, "stop": 1631722808974}], "start": 1631722808974, "stop": 1631722808974, "uuid": "11b453d4-7324-4339-892d-6186c270d662", "historyId": "8a681e6ad6324cc3950ebf67dcb242a2", "testCaseId": "9c5909de45c1f02bfeb5cae475b69172", "fullName": "testcases.test_c004_signin_400#test_c004_04_error_field", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_c004_signin_400"}, {"name": "host", "value": "QupsAnik"}, {"name": "thread", "value": "18880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_c004_signin_400"}]}