{"name": "test_c002_03_error_message", "status": "passed", "steps": [{"name": "Signup unsuccessful, error message validation", "status": "passed", "start": 1631722808958, "stop": 1631722808958}], "start": 1631722808958, "stop": 1631722808958, "uuid": "f79c2b33-c59a-4a22-83de-7014ca9a98f6", "historyId": "1f40305c7c9282f4030fe28dd196c1bf", "testCaseId": "02ca7cf529a6558dd1d0c7ab10572292", "fullName": "testcases.test_c002_signup_400#test_c002_03_error_message", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_c002_signup_400"}, {"name": "host", "value": "QupsAnik"}, {"name": "thread", "value": "18880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_c002_signup_400"}]}